---
title: "Homework - Week 8"
author: "Vasco Brazão"
output:
  html_document:
    keep_md: yes
  pdf_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE, warning = FALSE}
library(rethinking)
library(tidybayes)
library(tidyverse)
library(here)


set.seed(02072022)
```

## 1

```{r one.data}
d1_raw <- readr::read_csv(file = here::here("homework", "week-8_vasco", "week08_Monks.csv"))

d1 <- list(
  N_dyads = nrow(d1_raw),
  D = d1_raw$dyad_id,
  like_AB = d1_raw$like_AB,
  like_BA = d1_raw$like_BA
)
```

We adapt the model of the lecture for this.

```{r one.model}
f_1 <- alist(
  like_AB ~ binomial(3, pAB),
  like_BA ~ binomial(3, pBA),
  logit(pAB) <- a + T[D,1],
  logit(pBA) <- a + T[D,2],
  a ~ normal(0, 1),
  
  ## dyad effects
  transpars> matrix[N_dyads, 2]:T <- compose_noncentered(rep_vector(sigma_T, 2), L_Rho_T, Z),
  matrix[2, N_dyads]:Z ~ normal(0, 1),
  cholesky_factor_corr[2]:L_Rho_T ~ lkj_corr_cholesky(2),
  sigma_T ~ exponential(1),
  
  ## corr matrix for dyads
  gq> matrix[2,2]:Rho_T <<- Chol_to_Corr(L_Rho_T) 
)

m1 <- rethinking::ulam(
  f_1, data = d1, chains = 4, cores = 4, iter = 2000
)

precis(m1, depth = 3, pars = c("a", "Rho_T", "sigma_T"))
```

So the correlation of likes within dyad seems to be reliable positive (.45 to .79). However, we haven't taken important features of the data into account yet.

